#!/usr/bin/env bash
run_detekt() {
  echo "Running detekt check in ${1}..."
  OUTPUT="/tmp/detekt-$(date +%s)"
  (cd "$1" && ./gradlew detekt) > $OUTPUT
  EXIT_CODE=$?
  if [ $EXIT_CODE -ne 0 ]; then
    cat $OUTPUT
    rm $OUTPUT
    echo "***********************************************"
    echo "                 detekt failed                 "
    echo " Please fix the above issues before committing "
    echo "***********************************************"
    exit $EXIT_CODE
  fi
  rm $OUTPUT
}

run_detekt .
